function iris = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IRIS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  IRIS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  iris = importfile("C:\Users\Jose Emilio Regio\ML Projects\Iris\iris.data", [1, 150]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Mar-2022 22:48:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, 150];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["sepalLength", "sepalWidth", "petalLength", "petalWidth", "class"];
opts.VariableTypes = ["double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "class", "EmptyFieldRule", "auto");

% Import the data
iris = readtable(filename, opts);

end